version: '3'

services:
  # web-client:
  #   build: 
  #     context: ./web-client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./web-client:/app
  #     - /app/node_modules

  # discord-bot:
  #   build: 
  #     context: ./discord-bot
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./discord-bot:/usr/src/app
  #   environment:
  #     - DISCORD_TOKEN=your_discord_token

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "1323:1323"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mariadb
      - DB_NAME=tibiago

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=tibiago
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: